name: Publish Release - Python

on:
  push:
    tags:
      - "v*"

  workflow_dispatch:

env:
  UV_VERSION: "0.7.20"

jobs:
  build-n-publish:
    name: Build and publish to PyPI
    if: github.repository == 'run-llama/llama_cloud_services'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: ${{ env.UV_VERSION }}

      - name: Set up Python
        run: uv python install

      - name: Display Python version
        run: python --version

      - name: Build
        working-directory: py
        run: uv build

      - name: Test installing built package
        shell: bash
        working-directory: py
        run: |
          uv venv
          uv pip install dist/*.whl

      - name: Publish package
        shell: bash
        working-directory: py
        run: uv publish --token ${{ secrets.LLAMA_PARSE_PYPI_TOKEN }}

      - name: Build and publish llama-parse
        working-directory: py/llama_parse/
        run: |
          uv build
          uv publish --token ${{ secrets.LLAMA_PARSE_PYPI_TOKEN }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }} - LlamaCloud Services PY
          artifacts: "py/**/dist/*"
          generateReleaseNotes: true
          draft: false
          prerelease: false
