name: Publish Release - TypeScript

on:
  push:
    tags:
      - "llama-cloud-services@*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "ts/llama_cloud_services/.nvmrc"

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run Build
        working-directory: ts/llama_cloud_services/
        run: pnpm build

      - name: Build tarball
        run: |
          pnpm pack
        working-directory: ts/llama_cloud_services

      - name: Setup npm authentication
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Release
        working-directory: ts/llama_cloud_services
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm publish --access public --no-git-checks

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "ts/llama_cloud_services/llama-cloud-services*.tgz"
          name: Release ${{ github.ref }} - LlamaCloud Services TS
          bodyFile: "ts/llama_cloud_services/CHANGELOG.md"
          token: ${{ secrets.GITHUB_TOKEN }}
